### ISSUE TITLE
No longer available on Google Assistant?

### ISSUE THREAD

**Issue by vaguerant** [SysCoder/voice-tic-tac-toe#1]
Sorry for misusing issues, I know this isn't one but couldn't find a better way to contact you short of registering a Twitter account or something.

Is Voice Tic-Tac-Toe no longer available as a Google Assistant app? I received a Google Home Mini for Christmas and was really interested to find that such an app existed for it. However, when I ask Assistant to play Voice Tic-Tac-Toe, it replies that it isn't available in my region (I'm in Australia, although Assistant's language is set to US English).

Trying to look up the app online, its page on assistant.google.com simply 404s: https://assistant.google.com/services/a/id/067599fbb2773ca9/

Thanks for any advice you can offer, and best of luck with Voice Tic-Tac-Toe on the Echo Spot!

**Comment by SysCoder** [comment]
Oh... I am sorry to hear that :-(

 I made the game available for kids which made it only available in the United States. 

"Apps participating in the Apps for Families program must meet all the requirements in this section and comply with the Terms of Service for Actions on Google, including the Apps for Families Addendum. The Apps for Families program is currently only available to Assistant Apps offered in the United States."
https://developers.google.com/actions/policies/general-policies#apps_for_families

**Comment by vaguerant** [comment]
Ah, that's a shame, but understandable. Fingers crossed Google will expand the program internationally. Thanks for the rapid response!

**Comment by SysCoder** [comment]
No problem!
If you are interested in creating voice apps for yourself, I made a step by step tutorial on Youtube.
https://www.youtube.com/channel/UCioGNuydU_b5vg66O4FiLDw
